name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-formatting:
    name: Verify Formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Verify Formatting
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "20"

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        architecture:
          #- x86
          - x64
        include:
          - configuration: Debug
            preset: debug
          - configuration: Release
            preset: release
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ matrix.architecture }}

      - name: CMake Build
        run: cmake --workflow --preset=${{matrix.preset}}

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        if: "${{ matrix.configuration == 'Release' }}"
        with:
          name: Windows ${{ matrix.architecture }} ${{matrix.configuration}} Binaries
          path: |
            deps/ida-sdk/src/bin/plugins/function-string-associate.dll
            deps/ida-sdk/src/bin/plugins/function-string-associate.pdb

  summary:
    name: Pipeline Summary
    runs-on: ubuntu-24.04
    needs: [build-windows, verify-formatting]
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v5
        continue-on-error: true
        with:
          name: "Temp *"

      - name: Pipeline failed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
